export const UPDATE_APP_BAR = 'UPDATE_APP_BAR'

export const CREATE_PEDIDO = 'CREATE_PEDIDO'
export const CREATE_PEDIDO_SUCCESS = 'CREATE_PEDIDO_SUCCESS'

export const CREATE_DASHBOARD = 'CREATE_DASHBOARD'
export const CREATE_DASHBOARD_SUCCESS = 'CREATE_DASHBOARD_SUCCESS'

export const LOAD_DASHBOARD = 'LOAD_DASHBOARD'
export const LOAD_DASHBOARD_SUCCESS = 'LOAD_DASHBOARD_SUCCESS'

export const LOAD_PEDIDO = 'LOAD_PEDIDO'
export const REMOVE_PEDIDO = 'REMOVE_PEDIDO'
export const UPDATE_STATUS_PEDIDO = 'UPDATE_STATUS_PEDIDO'

export const LOAD_ALL_PEDIDOS = 'LOAD_ALL_PEDIDOS'
export const LOAD_ALL_PEDIDOS_SUCCESS = 'LOAD_ALL_PEDIDOS_SUCCESS'

export const LOAD_APP_SUCCESS = 'LOAD_APP_SUCCESS'
export const CHANGE_TITLE = 'CHANGE_TITLE'
export const CHANGE_BOTTOM_BAR = 'CHANGE_BOTTOM_BAR'


